export const instructions = [
  {
    title: 'Choose a category',
    description:
      'First, choose a word category, like animals or movies. The computer then randomly selects a secret word from that topic and shows you blanks for each letter of the word.',
  },
  {
    title: 'Guess letters',
    description:
      'Take turns guessing letters. The computer fills in the relevant blank spaces if your guess is correct. If it’s wrong, you lose some health, which empties after eight incorrect guesses.',
  },
  {
    title: 'Win or lose',
    description:
      'You win by guessing all the letters in the word before your health runs out. If the health bar empties before you guess the word, you lose.',
  },
];

export const word_categories = [
  'Animals',
  'Movies',
  'Fruits',
  'Countries',
  'Jobs',
  'Sports',
  'Transportation',
  'Colors',
];

export const english_characters = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
];

export const words = {
  animals: [
    'cat',
    'dog',
    'tiger',
    'lion',
    'zebra',
    'monkey',
    'rabbit',
    'panda',
    'elephant',
    'giraffe',
    'kangaroo',
    'dolphin',
    'whale',
    'eagle',
    'penguin',
  ],

  movies: [
    'avatar',
    'titanic',
    'inception',
    'gladiator',
    'rocky',
    'alien',
    'matrix',
    'jaws',
    'coco',
    'frozen',
    'gravity',
    'up',
    'cars',
    'dune',
  ],

  fruits: [
    'apple',
    'banana',
    'orange',
    'grape',
    'mango',
    'papaya',
    'peach',
    'pear',
    'cherry',
    'melon',
    'lemon',
    'coconut',
    'plum',
  ],

  countries: [
    'canada',
    'brazil',
    'germany',
    'france',
    'italy',
    'spain',
    'japan',
    'korea',
    'thailand',
    'vietnam',
    'india',
    'egypt',
    'turkey',
    'norway',
  ],

  jobs: [
    'doctor',
    'teacher',
    'engineer',
    'designer',
    'developer',
    'nurse',
    'lawyer',
    'chef',
    'pilot',
    'farmer',
    'writer',
    'artist',
    'manager',
  ],

  sports: [
    'soccer',
    'tennis',
    'cricket',
    'baseball',
    'golf',
    'boxing',
    'hockey',
    'rugby',
    'cycling',
    'swimming',
    'badminton',
    'volleyball',
  ],

  transportation: [
    'car',
    'bus',
    'train',
    'plane',
    'bicycle',
    'motorcycle',
    'truck',
    'subway',
    'tram',
    'boat',
    'ferry',
    'rocket',
  ],

  colors: [
    'red',
    'blue',
    'green',
    'yellow',
    'purple',
    'orange',
    'pink',
    'brown',
    'black',
    'white',
    'gray',
    'cyan',
    'magenta',
  ],
};
